import { useMemo, useState } from 'react';
import { BarChart3, Download, Info } from 'lucide-react';
import EmptyState from '../components/EmptyState.jsx';
import Metric from '../components/Metric.jsx';
import TrendChart from '../components/TrendChart.jsx';
import { EXPENSE_CATEGORIES } from '../constants.js';
import { fmtMoney, fmtNum } from '../lib/helpers.js';
import { availableYears, buildComprehensiveAnalysis, buildExpenseAnalysis, buildFeedAnalysis, buildProductionAnalysis, buildYearOverYear, downloadComprehensiveAnalysis } from '../lib/analytics.js';
import { buildFinancialAnalysis } from '../lib/financialAnalytics.js';

const today = new Date().toISOString().slice(0, 10);
export default function AnalyticsView({ units, logs, expenses, inventory = [], inventoryMoves = [] }) {
 const data=useMemo(()=>({units,logs,expenses,inventory,inventoryMoves}),[units,logs,expenses,inventory,inventoryMoves]); const years=useMemo(()=>availableYears(data),[data]); const defaultYear=years[0]||new Date().getFullYear();
 const [unitId,setUnitId]=useState('all'),[itemId,setItemId]=useState('all'),[expenseType,setExpenseType]=useState('all'),[startDate,setStartDate]=useState(`${defaultYear}-01-01`),[endDate,setEndDate]=useState(defaultYear===new Date().getFullYear()?today:`${defaultYear}-12-31`),[analysis,setAnalysis]=useState('overview');
 const filters={unitId,itemId,expenseType,startDate,endDate}; const feed=useMemo(()=>buildFeedAnalysis(data,filters),[data,unitId,itemId,startDate,endDate]); const expense=useMemo(()=>buildExpenseAnalysis(data,filters),[data,unitId,expenseType,startDate,endDate]); const production=useMemo(()=>buildProductionAnalysis(data,filters),[data,unitId,startDate,endDate]); const yoy=useMemo(()=>buildYearOverYear(data,filters),[data,unitId,startDate,endDate]); const filtered=useMemo(()=>buildComprehensiveAnalysis(data,filters),[data,unitId,itemId,expenseType,startDate,endDate]); const financial=useMemo(()=>buildFinancialAnalysis(data,filters),[data,unitId,expenseType,startDate,endDate]);
 if(!units.length)return <EmptyState icon={BarChart3} title="Nothing to look at yet" body="Add a farm group and records, or import your historical records, to build analysis from real farm data."/>;
 const selectedUnit=units.find(u=>u.id===unitId),feedTrend=feed.monthly.map(r=>({date:`${r.month}-01`,value:r.value})),productionTrend=production.byMonth.map(r=>({date:`${r.month}-01`,value:r.value}));
 return <div className="space-y-5"><header><div className="text-xs font-semibold uppercase tracking-[0.16em]" style={{color:'var(--forest)'}}>Analytics</div><h1 className="font-display text-2xl font-semibold mt-1">Analysis Builder</h1><p className="text-sm mt-1" style={{color:'var(--ink-soft)'}}>See production, revenue, expenses and profit together, then drill into feed and operating costs.</p></header>
 <section className="rounded-2xl p-4 sm:p-5 space-y-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><Filter label="Farm group"><select value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="all">All farm groups</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Filter><Filter label="Feed / stock item"><select value={itemId} onChange={e=>setItemId(e.target.value)}><option value="all">All items</option>{inventory.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Filter><Filter label="Expense type"><select value={expenseType} onChange={e=>setExpenseType(e.target.value)}><option value="all">All expense types</option>{EXPENSE_CATEGORIES.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}<option value="other">Other</option></select></Filter><Filter label="Year"><select value={startDate.slice(0,4)} onChange={e=>{const y=e.target.value;if(y==='custom')return;setStartDate(`${y}-01-01`);setEndDate(y===String(new Date().getFullYear())?today:`${y}-12-31`);}}><option value="custom">Custom dates</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></Filter></div><div className="grid grid-cols-2 gap-3 max-w-xl"><Filter label="From"><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></Filter><Filter label="To"><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></Filter></div><div className="flex flex-wrap gap-2 pt-1">{['overview','feed','expenses','production'].map(key=><button key={key} type="button" onClick={()=>setAnalysis(key)} className={`tag-chip ${analysis===key?'active':''}`}>{key[0].toUpperCase()+key.slice(1)}</button>)}<button type="button" className="btn-primary rounded-xl px-3 py-2 text-sm inline-flex items-center gap-2 ml-auto" onClick={()=>downloadComprehensiveAnalysis(data,filters)}><Download size={15}/> Download this analysis</button></div></section>
 <section className="grid grid-cols-2 sm:grid-cols-4 gap-3"><Summary label="Revenue" value={fmtMoney(financial.revenue)} accent="var(--forest)"/><Summary label="Expenses" value={fmtMoney(financial.expenses)}/><Summary label="Profit" value={fmtMoney(financial.profit)} accent={financial.profit>=0?'var(--forest)':'var(--rust)'}/><Summary label="Production" value={fmtNum(filtered.summary.production)}/></section>
 {analysis==='overview'&&<Overview production={production} expense={expense} yoy={yoy} financial={financial}/>} {analysis==='feed'&&<FeedAnalysis feed={feed} unit={selectedUnit} trend={feedTrend}/>} {analysis==='expenses'&&<ExpenseAnalysis expense={expense}/>} {analysis==='production'&&<ProductionAnalysis production={production} trend={productionTrend}/>}<div className="rounded-2xl p-4 text-xs flex gap-2" style={{background:'var(--surface)',border:'1px solid var(--line)',color:'var(--ink-soft)'}}><Info size={14}/><span>{selectedUnit?`${selectedUnit.name} is selected.`:'All farm groups are selected.'} Revenue is estimated from each group's saved selling price.</span></div></div>;
}
function Filter({label,children}){return <label className="block text-sm"><span className="text-xs font-medium" style={{color:'var(--ink-soft)'}}>{label}</span><div className="mt-1">{children}</div></label>}
function Summary({label,value,accent}){return <div className="rounded-2xl p-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="text-xs" style={{color:'var(--ink-soft)'}}>{label}</div><div className="font-mono text-lg font-semibold mt-1 break-words" style={{color:accent}}>{value}</div></div>}
function Panel({title,children}){return <section className="rounded-2xl p-5" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><h2 className="font-semibold mb-4">{title}</h2>{children}</section>}
function Overview({production,expense,yoy,financial}){return <div className="space-y-4"><Panel title="Financial result"><div className="grid grid-cols-3 gap-4"><Metric label="Revenue" value={fmtMoney(financial.revenue)}/><Metric label="Expenses" value={fmtMoney(financial.expenses)}/><Metric label="Profit" value={fmtMoney(financial.profit)} accent={financial.profit>=0?'var(--forest)':'var(--rust)'}/></div></Panel><Panel title="Production trend"><TrendChart data={production.byMonth.map(r=>({date:`${r.month}-01`,value:r.value}))}/></Panel><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Panel title="Expense mix"><div className="space-y-2">{expense.byType.map(r=><div key={r.type} className="flex justify-between text-sm"><span>{r.type}</span><span className="font-mono">{fmtMoney(r.amount)}</span></div>)}</div></Panel><Panel title="Year-over-year"><Metric label="Production change" value={yoy?.change.production!=null?`${yoy.change.production.toFixed(1)}%`:'—'} accent={yoy?.change.production>=0?'var(--forest)':'var(--rust)'}/><Metric label="Expense change" value={yoy?.change.expenses!=null?`${yoy.change.expenses.toFixed(1)}%`:'—'} accent={yoy?.change.expenses<=0?'var(--forest)':'var(--rust)'}/></Panel></div></div>}
function FeedAnalysis({feed,unit,trend}){return <div className="space-y-4"><Panel title={`${unit?.name||'Farm'} — Feed analysis`}><div className="grid grid-cols-2 sm:grid-cols-4 gap-4"><Metric label="Consumed" value={`${fmtNum(feed.consumption,1)} kg`}/><Metric label="Purchases" value={`${fmtNum(feed.purchases,1)} kg`}/><Metric label="Wastage" value={`${fmtNum(feed.wastage,1)} kg`}/><Metric label="Feed cost" value={fmtMoney(feed.feedCost)}/></div></Panel><Panel title="Monthly feed consumption"><TrendChart data={trend}/></Panel></div>}
function ExpenseAnalysis({expense}){return <div className="space-y-4"><Panel title="Expense types"><div className="space-y-2">{expense.byType.map(r=><div key={r.type} className="flex justify-between"><span>{r.type}</span><span className="font-mono">{fmtMoney(r.amount)}</span></div>)}</div></Panel><Panel title="Monthly expenses"><TrendChart data={expense.byMonth.map(r=>({date:`${r.month}-01`,value:r.value}))}/></Panel></div>}
function ProductionAnalysis({production,trend}){return <div className="space-y-4"><Panel title="Production metrics"><div className="grid grid-cols-2 sm:grid-cols-3 gap-4"><Metric label="Produced" value={fmtNum(production.total)}/><Metric label="Losses" value={fmtNum(production.loss)}/><Metric label="Mortality" value={fmtNum(production.mortality)}/></div></Panel><Panel title="Monthly production"><TrendChart data={trend}/></Panel></div>}
