import { useState } from 'react';
import { BarChart3, ChevronDown, ChevronUp, Info, TrendingUp, TrendingDown, Boxes, Receipt } from 'lucide-react';
import TagChip from '../components/TagChip.jsx';
import EmptyState from '../components/EmptyState.jsx';
import Metric from '../components/Metric.jsx';
import TrendChart from '../components/TrendChart.jsx';
import { PERIODS } from '../constants.js';
import { typeOf, unitMetrics, unitCostBreakdown, dailyProductionTrend, fmtNum, fmtMoney, inventoryUnitCost, inPeriod } from '../lib/helpers.js';

export default function AnalyticsView({ units, logs, expenses, inventory = [], inventoryMoves = [] }) {
 const [period,setPeriod]=useState('all');
 if(!units.length)return <EmptyState icon={BarChart3} title="Nothing to look at yet" body="Add a farm group and a few records to see your farm history here."/>;
 const periodExpenses=expenses.filter(e=>inPeriod(e.date,period));
 const periodLogs=logs.filter(l=>inPeriod(l.date,period));
 const periodMoves=inventoryMoves.filter(m=>inPeriod(m.date,period));
 const totalSpent=periodExpenses.reduce((s,e)=>s+(Number(e.amount)||0),0);
 const totalProduced=periodLogs.reduce((s,l)=>s+(Number(l.produced)||0),0);
 const stockValue=inventory.reduce((s,item)=>s+(Number(item.unitCost)||inventoryUnitCost(item,inventoryMoves))*(Number(item.openingStock)||0)+inventoryMoves.filter(m=>m.itemId===item.id&&(m.direction||m.type)==='in').reduce((x,m)=>x+(Number(m.quantity)||0)*(Number(m.unitCost)||0),0),0);
 return <div className="space-y-5">
  <div className="flex gap-2 flex-wrap">{PERIODS.map(p=><TagChip key={p.value} label={p.label} active={period===p.value} onClick={()=>setPeriod(p.value)}/>)}</div>
  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
   <Summary icon={BarChart3} label="Farm groups" value={units.length}/><Summary icon={BarChart3} label="Produced" value={fmtNum(totalProduced)}/><Summary icon={Receipt} label="Spent" value={fmtMoney(totalSpent)}/><Summary icon={Boxes} label="Stock items" value={inventory.length}/>
  </div>
  <div className="rounded-2xl p-4 text-sm" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="font-semibold">Historical records included</div><div className="mt-1" style={{color:'var(--ink-soft)'}}>{period==='all'?`All ${logs.length} production logs, ${expenses.length} expenses and ${inventoryMoves.length} stock movements are included.`:`This view includes ${periodLogs.length} production logs, ${periodExpenses.length} expenses and ${periodMoves.length} stock movements for the selected period.`}</div></div>
  <div className="space-y-3.5">{units.map(u=><UnitAnalyticsCard key={u.id} unit={u} logs={logs} expenses={expenses} inventory={inventory} inventoryMoves={inventoryMoves} period={period}/>)}</div>
  <div className="flex items-start gap-2 text-xs px-1" style={{color:'var(--ink-soft)'}}><Info size={13} className="mt-0.5 shrink-0"/><span>Imported records use their original dates. Choose “All time” to review the full history.</span></div>
 </div>;
}
function Summary({icon:Icon,label,value}){return <div className="rounded-2xl p-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><Icon size={16} style={{color:'var(--forest)'}}/><div className="text-xs mt-2" style={{color:'var(--ink-soft)'}}>{label}</div><div className="font-mono text-lg font-semibold mt-1 break-words">{value}</div></div>;}
function UnitAnalyticsCard({unit,logs,expenses,inventory,inventoryMoves,period}){const [expanded,setExpanded]=useState(false);const t=typeOf(unit),Icon=t.icon,m=unitMetrics(unit,logs,expenses,period,inventoryMoves),singular=t.unitLabel.replace(/s$/,'');const costs=unitCostBreakdown(unit,logs,expenses,period,inventoryMoves,inventory),trend=dailyProductionTrend(unit,logs,14),hasPrice=Number(unit.producePrice)>0;return <div className="rounded-2xl p-5" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="flex items-center gap-2 mb-4"><Icon size={16} style={{color:'var(--forest)'}}/><div className="font-display text-lg font-semibold break-words">{unit.name}</div><div className="text-xs ml-auto font-mono" style={{color:'var(--ink-soft)'}}>{m.logCount} {m.logCount===1?'entry':'entries'}</div></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-4"><Metric label={`Cost per ${singular}`} value={m.costPerUnit!==null?fmtMoney(m.costPerUnit,2):'—'}/><Metric label="Spent this period" value={fmtMoney(m.directCost)}/><Metric label="Produced" value={`${fmtNum(m.produced)} ${t.unitLabel}`}/></div>{hasPrice&&<div className="flex items-center gap-2.5 mt-4 pt-4 text-sm" style={{borderTop:'1px solid var(--line)'}}><span style={{color:'var(--ink-soft)'}}>Revenue {fmtMoney(m.revenue)}</span><span style={{color:'var(--ink-soft)'}}>→</span><span className="inline-flex items-center gap-1 font-semibold" style={{color:m.profit>=0?'var(--forest)':'var(--rust)'}}>{m.profit>=0?<TrendingUp size={14}/>:<TrendingDown size={14}/>}Profit {fmtMoney(m.profit)}</span></div>}<div className="mt-4 pt-4" style={{borderTop:'1px solid var(--line)'}}><div className="text-xs mb-1.5" style={{color:'var(--ink-soft)'}}>Recent production, last 14 days</div><TrendChart data={trend}/></div><button type="button" onClick={()=>setExpanded(v=>!v)} className="flex items-center gap-1 text-xs font-medium mt-4" style={{color:'var(--forest)'}}>{expanded?<ChevronUp size={14}/>:<ChevronDown size={14}/>} {expanded?'Show less':'See more details'}</button>{expanded&&<div className="mt-4 pt-4 space-y-4" style={{borderTop:'1px solid var(--line)'}}>{costs.length>0&&<div><div className="text-xs mb-2" style={{color:'var(--ink-soft)'}}>Where the money went</div><div className="space-y-1.5">{costs.map(r=><CostBar key={r.label} {...r} max={costs[0].amount}/>)}</div></div>}<div className="grid grid-cols-2 sm:grid-cols-3 gap-4"><Metric label="Feed used" value={m.feedKg>0?`${fmtNum(m.feedKg,1)} kg`:'—'}/><Metric label={`Feed per ${singular}`} value={m.fcr!==null?`${m.fcr.toFixed(2)} kg`:'—'}/>{t.hasGrades&&<Metric label="Laying rate" value={m.productionRate!==null?`${m.productionRate.toFixed(1)}%`:'—'}/>}<Metric label="Losses" value={m.mortalityRate!==null?`${m.mortalityRate.toFixed(1)}%`:'—'} accent={m.mortalityRate>5?'var(--rust)':undefined}/></div></div>}</div>}
function CostBar({label,amount,max}){const pct=max>0?Math.max(4,(amount/max)*100):0;return <div><div className="flex justify-between text-xs mb-1"><span style={{color:'var(--ink)'}}>{label}</span><span className="font-mono" style={{color:'var(--ink-soft)'}}>{fmtMoney(amount)}</span></div><div className="rounded-full overflow-hidden" style={{background:'var(--surface-alt)',height:6}}><div className="h-full rounded-full" style={{width:`${pct}%`,background:'var(--forest)'}}/></div></div>;}
