import { useEffect, useState } from 'react';
import { ClipboardList, Trash2, Pencil, X, Save, Plus } from 'lucide-react';
import TagChip from '../components/TagChip.jsx'; import FieldLabel from '../components/FieldLabel.jsx'; import EmptyState from '../components/EmptyState.jsx';
import { inputClass, inputStyle } from '../lib/styleTokens.js'; import { UNIT_TYPES } from '../constants.js'; import { uid, todayISO, typeOf, fmtNum } from '../lib/helpers.js';
const emptyInput=()=>({itemId:'',quantity:'',kind:'feed'});
export default function DailyLogView({units,logs,inventory=[],getBalance,onAdd,onUpdate,onRemove,goTo}){
 const [unitId,setUnitId]=useState(units[0]?.id||''),[date,setDate]=useState(todayISO()),[large,setLarge]=useState(''),[medium,setMedium]=useState(''),[small,setSmall]=useState(''),[broken,setBroken]=useState(''),[qty,setQty]=useState(''),[loss,setLoss]=useState(''),[mortality,setMortality]=useState(''),[notes,setNotes]=useState(''),[editingId,setEditingId]=useState(null),[inputs,setInputs]=useState([emptyInput()]);
 const unit=units.find(u=>u.id===unitId); useEffect(()=>{if(!unitId&&units[0])setUnitId(units[0].id)},[units,unitId]);
 if(!units.length)return <EmptyState icon={ClipboardList} title="Add a farm group before logging" body="Daily logs are recorded against a specific animal, flock, herd, or plot." actionLabel="Add a farm group" onAction={()=>goTo('units')}/>;
 const t=unit?typeOf(unit):UNIT_TYPES[0];
 const changeInput=(index,key,value)=>setInputs(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row)); const addInput=()=>setInputs(rows=>[...rows,emptyInput()]); const removeInput=index=>setInputs(rows=>rows.length===1?[emptyInput()]:rows.filter((_,i)=>i!==index));
 function editLog(l){setEditingId(l.id);setUnitId(l.unitId);setDate(l.date);setMortality(String(l.mortality||0));setNotes(l.notes||'');setInputs(Array.isArray(l.inputs)&&l.inputs.length?l.inputs.map(x=>({...x,quantity:String(x.quantity)})):l.feedItemId?[{itemId:l.feedItemId,quantity:String(l.feedQuantity??l.feedKg??''),kind:'feed'}]:[emptyInput()]);if(l.grades){setLarge(String(l.grades.large||0));setMedium(String(l.grades.medium||0));setSmall(String(l.grades.small||0));setBroken(String(l.loss||0))}else{setQty(String(l.produced||0));setLoss(String(l.loss||0))}window.scrollTo({top:0,behavior:'smooth'})}
 function reset(){setLarge('');setMedium('');setSmall('');setBroken('');setQty('');setLoss('');setMortality('');setNotes('');setInputs([emptyInput()]);setEditingId(null)}
 function submit(ev){ev.preventDefault();if(!unit)return;let produced=0,grades=null;if(t.hasGrades){const L=Number(large)||0,M=Number(medium)||0,S=Number(small)||0;produced=L+M+S;grades={large:L,medium:M,small:S}}else produced=Number(qty)||0;const cleanInputs=inputs.filter(x=>x.itemId&&Number(x.quantity)>0).map(x=>({...x,quantity:Number(x.quantity)}));const firstFeed=cleanInputs.find(x=>x.kind==='feed');const entry={id:editingId||uid('log'),unitId:unit.id,date,produced,grades,loss:t.hasGrades?Number(broken)||0:Number(loss)||0,inputs:cleanInputs,feedKg:firstFeed?.quantity||0,feedQuantity:firstFeed?.quantity||0,feedItemId:firstFeed?.itemId||null,mortality:Number(mortality)||0,notes:notes.trim(),createdAt:editingId?logs.find(l=>l.id===editingId)?.createdAt||Date.now():Date.now()};const saved=editingId?onUpdate(entry):onAdd(entry,unit);if(saved!==false)reset()}
 const recent=logs.filter(l=>l.unitId===unitId).sort((a,b)=>a.date<b.date?1:-1).slice(0,6);
 return <div className="space-y-6"><div><FieldLabel>Farm group / animal</FieldLabel><div className="flex gap-2 flex-wrap">{units.map(u=>{const Icon=typeOf(u).icon;return <TagChip key={u.id} label={u.name} icon={Icon} active={u.id===unitId} onClick={()=>setUnitId(u.id)}/>})}</div></div><form onSubmit={submit} className="rounded-2xl p-5 space-y-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}>
 <div className="grid grid-cols-2 gap-3.5"><div><FieldLabel>Date</FieldLabel><input type="date" value={date} max={todayISO()} onChange={e=>setDate(e.target.value)} required className={inputClass} style={inputStyle}/></div><div><FieldLabel>Mortality / losses (animals)</FieldLabel><input type="number" min="0" value={mortality} onChange={e=>setMortality(e.target.value)} placeholder="0" className={inputClass} style={inputStyle}/></div></div>
 {t.hasGrades?<div><FieldLabel>Eggs collected, by grade</FieldLabel><div className="grid grid-cols-4 gap-2.5">{[['Large',large,setLarge],['Medium',medium,setMedium],['Small',small,setSmall],['Broken',broken,setBroken]].map(([label,value,setter])=><div key={label}><div className="text-xs mb-1" style={{color:'var(--ink-soft)'}}>{label}</div><input type="number" min="0" value={value} onChange={e=>setter(e.target.value)} placeholder="0" className={inputClass} style={inputStyle}/></div>)}</div></div>:<div className="grid grid-cols-2 gap-3.5"><div><FieldLabel>Quantity produced ({t.unitLabel})</FieldLabel><input type="number" min="0" step="0.1" value={qty} onChange={e=>setQty(e.target.value)} className={inputClass} style={inputStyle}/></div><div><FieldLabel>Loss / spoilage ({t.unitLabel})</FieldLabel><input type="number" min="0" step="0.1" value={loss} onChange={e=>setLoss(e.target.value)} className={inputClass} style={inputStyle}/></div></div>}
 <div className="space-y-2"><div className="flex justify-between items-center"><FieldLabel>Feed, medicine & other stock used — optional</FieldLabel><button type="button" onClick={addInput} className="btn-ghost rounded-lg px-2 py-1 text-xs flex items-center gap-1"><Plus size={13}/> Add item</button></div>{inputs.map((row,index)=>{const item=inventory.find(i=>i.id===row.itemId);return <div key={index} className="grid grid-cols-[1fr_110px_100px_auto] gap-2 mobile-stack-form"><select value={row.itemId} onChange={e=>changeInput(index,'itemId',e.target.value)} className={inputClass} style={inputStyle}><option value="">Select stock item</option>{inventory.map(i=><option key={i.id} value={i.id}>{i.name} · {fmtNum(getBalance?getBalance(i.id):i.openingStock||0,1)} {i.unit}</option>)}</select><input type="number" min="0" step="0.1" value={row.quantity} onChange={e=>changeInput(index,'quantity',e.target.value)} placeholder={item?.unit||'Qty'} className={inputClass} style={inputStyle}/><select value={row.kind} onChange={e=>changeInput(index,'kind',e.target.value)} className={inputClass} style={inputStyle}><option value="feed">Feed</option><option value="medicine">Medicine</option><option value="supplement">Supplement</option><option value="other">Other</option></select><button type="button" onClick={()=>removeInput(index)} className="p-2" aria-label="Remove stock item"><X size={16}/></button></div>})}</div>
 <div><FieldLabel>Notes — optional</FieldLabel><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} className={inputClass} style={inputStyle}/></div><div className="flex gap-2 flex-wrap"><button type="submit" className="btn-primary rounded-xl px-5 py-2.5 text-sm flex items-center gap-2"><Save size={15}/>{editingId?'Save changes':'Save log entry'}</button>{editingId&&<button type="button" onClick={reset} className="btn-ghost rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><X size={15}/>Cancel</button>}</div></form>
 {recent.length>0&&<div className="rounded-2xl overflow-hidden" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="px-5 pt-4 pb-3 font-display text-lg font-semibold">Recent entries — {unit?.name}</div><table className="w-full text-sm ledger-table"><tbody>{recent.map(l=><tr key={l.id} className="font-mono"><td className="px-5 py-2.5">{l.date}</td><td className="px-3 py-2.5 text-right">{fmtNum(l.produced)} {t.unitLabel}</td><td className="px-3 py-2.5 text-right">{Array.isArray(l.inputs)?`${l.inputs.length} inputs`:l.feedItemId?'1 input':'—'}</td><td className="px-5 py-2.5 text-right"><button onClick={()=>editLog(l)} className="p-1" aria-label="Edit entry"><Pencil size={14}/></button><button onClick={()=>onRemove(l.id)} className="p-1" aria-label="Delete entry"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</div>
}
