import { useMemo, useState } from 'react';
import { Boxes, Trash2, ArrowDownToLine, ArrowUpFromLine, AlertTriangle, Pencil, X, Save, Scale } from 'lucide-react';
import FieldLabel from '../components/FieldLabel.jsx';
import EmptyState from '../components/EmptyState.jsx';
import { inputClass, inputStyle } from '../lib/styleTokens.js';
import { uid, todayISO, fmtNum, fmtMoney } from '../lib/helpers.js';

const DEFAULT_CATEGORIES = ['Feed','Seed','Fertilizer','Medicine','Packaging','Fuel','Supplies','Other'];

export default function InventoryView({ inventory, units = [], expenses = [], moves, onAddItem, onUpdateItem, onRemoveItem, onAddMove, onUpdateMove, onRemoveMove, getExpenseUnitCost, transactionTypes = [] }) {
  const [name,setName]=useState(''),[category,setCategory]=useState('Feed'),[unit,setUnit]=useState('kg'),[openingStock,setOpeningStock]=useState(''),[reorderLevel,setReorderLevel]=useState(''),[unitCost,setUnitCost]=useState(''),[editingItemId,setEditingItemId]=useState(null);
  const [moveItemId,setMoveItemId]=useState(inventory[0]?.id||''),[moveType,setMoveType]=useState('purchase'),[moveQty,setMoveQty]=useState(''),[moveCountQty,setMoveCountQty]=useState(''),[moveDate,setMoveDate]=useState(todayISO()),[moveNote,setMoveNote]=useState(''),[expenseId,setExpenseId]=useState(''),[unitId,setUnitId]=useState(''),[destinationUnitId,setDestinationUnitId]=useState(''),[editingMoveId,setEditingMoveId]=useState(null);

  const balances=useMemo(()=>Object.fromEntries(inventory.map(item=>[item.id,(item.openingStock||0)+moves.filter(m=>m.itemId===item.id).reduce((s,m)=>s+((m.direction || m.type)==='in'?Number(m.quantity):-Number(m.quantity)),0)])),[inventory,moves]);
  const purchaseExpenses = expenses.filter(e => e.inventoryItemId && Number(e.inventoryQuantity) > 0 && inventory.some(i => i.id === e.inventoryItemId) && !moves.some(m => m.source === 'expense-purchase' && m.sourceId === e.id));
  const selectedExpense = purchaseExpenses.find(e => e.id === expenseId);
  const selectedExpenseUnitCost = selectedExpense ? getExpenseUnitCost(selectedExpense) : null;

  function resetItem(){setName('');setCategory('Feed');setUnit('kg');setOpeningStock('');setReorderLevel('');setUnitCost('');setEditingItemId(null)}
  function editItem(i){setEditingItemId(i.id);setName(i.name);setCategory(i.category);setUnit(i.unit);setOpeningStock(String(i.openingStock||0));setReorderLevel(String(i.reorderLevel||0));setUnitCost(String(i.unitCost||0));window.scrollTo({top:0,behavior:'smooth'})}
  function addItem(e){e.preventDefault();if(!name.trim())return;const r={id:editingItemId||uid('inv'),name:name.trim(),category,unit,openingStock:Number(openingStock)||0,reorderLevel:Number(reorderLevel)||0,unitCost:Number(unitCost)||0,createdAt:editingItemId?(inventory.find(i=>i.id===editingItemId)?.createdAt||Date.now()):Date.now()};editingItemId?onUpdateItem(r):onAddItem(r);resetItem()}
  function resetMove(){setMoveQty('');setMoveCountQty('');setMoveNote('');setExpenseId('');setEditingMoveId(null);setMoveDate(todayISO());setMoveType('purchase');setUnitId('');setDestinationUnitId('');if(inventory[0])setMoveItemId(inventory[0].id)}
  function editMove(m){setEditingMoveId(m.id);setMoveItemId(m.itemId);setMoveType(m.transactionType || (m.type==='in'?'purchase':'consumption'));setMoveQty(String(m.quantity||''));setMoveCountQty(String(m.countQuantity??''));setMoveDate(m.date);setMoveNote(m.note||'');setExpenseId(m.expenseId||'');setUnitId(m.sourceUnitId||m.unitId||'');setDestinationUnitId(m.destinationUnitId||'');window.scrollTo({top:0,behavior:'smooth'})}
  function addMove(e){
    e.preventDefault();
    const item=inventory.find(i=>i.id===moveItemId); if(!item)return;
    const current=editingMoveId?moves.find(m=>m.id===editingMoveId):null;
    const isCount=moveType==='stock_count';
    const qty=Number(moveQty); const countQty=Number(moveCountQty);
    if(!moveItemId || (!isCount && (!qty||qty<=0)) || (isCount && (!Number.isFinite(countQty)||countQty<0)))return;
    const selectedExpense = purchaseExpenses.find(e=>e.id===expenseId);
    const effectiveCost=moveType==='purchase' && selectedExpenseUnitCost != null ? selectedExpenseUnitCost : Number(item.unitCost)||0;
    const typeMeta=transactionTypes.find(t=>t.value===moveType);
    const r={id:editingMoveId||uid('txn'),itemId:moveItemId,transactionType:moveType,quantity:isCount?0:qty,countQuantity:isCount?countQty:undefined,unit:item.unit,date:moveDate,note:moveNote.trim(),expenseId:moveType==='purchase'?(expenseId||null):null,unitCost:effectiveCost,source:current?.source||'manual',sourceId:current?.sourceId||null,unitId:unitId||current?.unitId||null,sourceUnitId:unitId||current?.sourceUnitId||null,destinationUnitId:destinationUnitId||current?.destinationUnitId||null,createdAt:editingMoveId?(current?.createdAt||Date.now()):Date.now(),type:typeMeta?.direction||current?.type||'in'};
    const saved=editingMoveId?onUpdateMove(r):onAddMove(r); if(saved!==false)resetMove();
  }
  const recentMoves=[...moves].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).slice(0,10);

  return <div className="space-y-6">
    <form onSubmit={addItem} className="rounded-2xl p-5 space-y-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}>
      <div className="font-display text-lg font-semibold">{editingItemId?'Edit inventory item':'Add inventory item'}</div>
      <div className="grid grid-cols-2 gap-3.5"><div><FieldLabel>Item name</FieldLabel><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Layer mash" required className={inputClass} style={inputStyle}/></div><div><FieldLabel>Category</FieldLabel><select value={category} onChange={e=>setCategory(e.target.value)} className={inputClass} style={inputStyle}>{DEFAULT_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div></div>
      <div className="grid grid-cols-2 gap-3.5 sm:grid-cols-4"><div><FieldLabel>Unit</FieldLabel><input value={unit} onChange={e=>setUnit(e.target.value)} required className={inputClass} style={inputStyle}/></div><div><FieldLabel>Opening stock</FieldLabel><input type="number" min="0" step="0.1" value={openingStock} onChange={e=>setOpeningStock(e.target.value)} className={inputClass} style={inputStyle}/></div><div><FieldLabel>Reorder level</FieldLabel><input type="number" min="0" step="0.1" value={reorderLevel} onChange={e=>setReorderLevel(e.target.value)} className={inputClass} style={inputStyle}/></div><div><FieldLabel>Fallback unit cost</FieldLabel><input type="number" min="0" step="0.01" value={unitCost} onChange={e=>setUnitCost(e.target.value)} className={inputClass} style={inputStyle}/></div></div>
      <div className="flex gap-2 flex-wrap"><button className="btn-primary rounded-xl px-5 py-2.5 text-sm flex items-center gap-2"><Save size={15}/>{editingItemId?'Save changes':'Add item'}</button>{editingItemId&&<button type="button" onClick={resetItem} className="btn-ghost rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><X size={15}/>Cancel</button>}</div>
    </form>

    {inventory.length===0?<EmptyState icon={Boxes} title="Inventory is ready to track" body="Add feed, seed, fertilizer, medicine, packaging, fuel, or any other stock item."/>:<div className="space-y-2.5">{inventory.map(item=>{const balance=balances[item.id]||0,low=balance<=(item.reorderLevel||0);return <div key={item.id} className="rounded-2xl px-5 py-4 flex items-center justify-between gap-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="min-w-0"><div className="flex items-center gap-2 font-medium"><Boxes size={15} style={{color:'var(--forest)'}}/>{item.name}{low&&<span className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full" style={{background:'var(--rust-tint)',color:'var(--rust)'}}><AlertTriangle size={11}/>Reorder</span>}</div><div className="text-xs mt-1" style={{color:'var(--ink-soft)'}}>{item.category} · fallback {fmtMoney(item.unitCost||0)} / {item.unit}</div></div><div className="text-right font-mono"><div className="text-lg font-semibold">{fmtNum(balance,1)} {item.unit}</div><div className="text-xs" style={{color:'var(--ink-soft)'}}>reorder at {fmtNum(item.reorderLevel,1)}</div></div><div className="flex gap-1"><button onClick={()=>editItem(item)} className="p-1.5 rounded hover:bg-black/5" aria-label="Edit inventory item"><Pencil size={15}/></button><button onClick={()=>onRemoveItem(item.id)} className="p-1.5 rounded hover:bg-black/5" aria-label="Delete inventory item"><Trash2 size={15}/></button></div></div>})}</div>}

    <div className="rounded-2xl px-5 py-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="font-display text-lg font-semibold">Inventory transaction ledger</div><div className="text-sm mt-1" style={{color:'var(--ink-soft)'}}>Every purchase, consumption, wastage, return, transfer, adjustment, sale, and stock count is recorded as a transaction. Balances are calculated from the ledger instead of being manually edited.</div></div>

    <form onSubmit={addMove} className="rounded-2xl p-5 space-y-4" style={{background:'var(--surface)',border:'1px solid var(--line)'}}>
      <div className="font-display text-lg font-semibold">{editingMoveId?'Edit stock movement':'Record stock movement'}</div>
      <div className="grid grid-cols-2 gap-3.5"><div><FieldLabel>Item</FieldLabel><select value={moveItemId} onChange={e=>{setMoveItemId(e.target.value);setExpenseId('')}} className={inputClass} style={inputStyle}>{inventory.map(i=><option key={i.id} value={i.id}>{i.name} — {fmtNum(balances[i.id],1)} {i.unit}</option>)}</select></div><div><FieldLabel>Transaction type</FieldLabel><select value={moveType} onChange={e=>{setMoveType(e.target.value);if(e.target.value!=='purchase')setExpenseId('')}} className={inputClass} style={inputStyle}>{transactionTypes.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></div></div>
      {moveType==='purchase' && <div><FieldLabel>Purchase expense — optional</FieldLabel><select value={expenseId} onChange={e=>setExpenseId(e.target.value)} className={inputClass} style={inputStyle}><option value="">Use item's fallback cost</option>{purchaseExpenses.filter(e=>e.inventoryItemId===moveItemId).map(e=><option key={e.id} value={e.id}>{e.date} · {fmtMoney(e.amount)} / {fmtNum(e.inventoryQuantity,2)} = {fmtMoney(getExpenseUnitCost(e))} per unit</option>)}</select>{selectedExpenseUnitCost != null && <div className="text-xs mt-1" style={{color:'var(--forest)'}}>Unit cost from expense: {fmtMoney(selectedExpenseUnitCost)} / {inventory.find(i=>i.id===moveItemId)?.unit}</div>}</div>}
      <div className="grid grid-cols-2 gap-3.5"><div>{moveType==='stock_count'?<><FieldLabel>Actual counted stock</FieldLabel><input type="number" min="0" step="0.1" value={moveCountQty} onChange={e=>setMoveCountQty(e.target.value)} required className={inputClass} style={inputStyle}/></>:<><FieldLabel>Quantity</FieldLabel><input type="number" min="0.1" step="0.1" value={moveQty} onChange={e=>setMoveQty(e.target.value)} required className={inputClass} style={inputStyle}/></>}</div><div><FieldLabel>Date</FieldLabel><input type="date" value={moveDate} max={todayISO()} onChange={e=>setMoveDate(e.target.value)} required className={inputClass} style={inputStyle}/></div></div>
      {moveType==='consumption' && <div><FieldLabel>Production unit — optional</FieldLabel><select value={unitId} onChange={e=>setUnitId(e.target.value)} className={inputClass} style={inputStyle}><option value="">No unit / general stock</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div>}
      {moveType==='transfer' && <div className="grid grid-cols-2 gap-3.5"><div><FieldLabel>From unit</FieldLabel><select value={unitId} onChange={e=>setUnitId(e.target.value)} required className={inputClass} style={inputStyle}><option value="">Select source</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div><FieldLabel>To unit</FieldLabel><select value={destinationUnitId} onChange={e=>setDestinationUnitId(e.target.value)} required className={inputClass} style={inputStyle}><option value="">Select destination</option>{units.filter(u=>u.id!==unitId).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div></div>}
      <div><FieldLabel>Note — optional</FieldLabel><input value={moveNote} onChange={e=>setMoveNote(e.target.value)} placeholder="Supplier, usage, adjustment..." className={inputClass} style={inputStyle}/></div>
      <div className="flex gap-2 flex-wrap"><button className="btn-primary rounded-xl px-5 py-2.5 text-sm flex items-center gap-2">{moveType==='purchase'||moveType==='return'||moveType==='adjustment_in'?<ArrowDownToLine size={15}/>:moveType==='stock_count'?<Scale size={15}/>:<ArrowUpFromLine size={15}/>} {editingMoveId?'Save changes':'Record movement'}</button>{editingMoveId&&<button type="button" onClick={resetMove} className="btn-ghost rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><X size={15}/>Cancel</button>}</div>
    </form>

    {recentMoves.length>0&&<div className="rounded-2xl overflow-hidden" style={{background:'var(--surface)',border:'1px solid var(--line)'}}><div className="px-5 pt-4 pb-3 font-display text-lg font-semibold" style={{borderBottom:'1px solid var(--line)'}}>Recent movements</div><table className="w-full text-sm ledger-table"><tbody>{recentMoves.map(m=>{const item=inventory.find(i=>i.id===m.itemId);return <tr key={m.id} className="font-mono"><td className="px-5 py-2.5" style={{color:'var(--ink-soft)'}}>{m.date}</td><td className="px-3 py-2.5 font-sans">{item?.name||'Removed item'}</td><td className="px-3 py-2.5 text-right">{m.type==='in'?'+':'-'}{fmtNum(m.quantity,1)} {m.unit}</td><td className="px-3 py-2.5 font-sans" style={{color:'var(--ink-soft)'}}>{m.source==='daily-log'?'Daily log':(transactionTypes.find(t=>t.value===m.transactionType)?.label || (m.expenseId?'Purchase expense':'Manual'))}{m.unitCost ? ` · ${fmtMoney(m.unitCost)}/${m.unit}` : ''}</td><td className="px-5 py-2.5 text-right"><div className="flex justify-end gap-1"><button onClick={()=>editMove(m)} className="p-1 rounded hover:bg-black/5" aria-label="Edit movement"><Pencil size={14}/></button><button onClick={()=>onRemoveMove(m.id)} className="p-1 rounded hover:bg-black/5" aria-label="Delete movement"><Trash2 size={14}/></button></div></td></tr>})}</tbody></table></div>}
  </div>
}
